app: # 应用基本配置
  env: local # 环境名称
  port: 8090 # 服务监听端口号8090
  app_name: gin-app # 应用名称
  app_url: http://localhost # 应用域名

database: # 数据库
  host: "127.0.0.1"
  port: 3306
  database: 'cs'
  charset: 'utf8mb4'
  username: 'root'
  password: 'root'

FileUploadSetting:
  Size: 32                            #设置上传文件的最大值，单位：M，注意： 如果go前置nginx服务器，nginx 默认限制文件上传大小为 50 M ,用户上传文件限制还需要继续修改 nginx 配置
  UploadFileField: "file"            #post上传文件时，表单的键名
  UploadFileSavePath: "./storage/uploaded/" #上传文件保存在路径, 该路径与 BasePath 进行拼接使用
  UploadFileReturnPath: "/public/storage/uploaded/"  # 文件上后返回的路径，由于程序会自动创建软连接，自动将资源定位到实际路径，所有资源的访问入口建议都从public开始

redis:
  host: 127.0.0.1
  port: 6379
  db: 0
  password:

email:
  address: "smtp.qq.com:25"
  identity: ""
  username: "2943785277@qq.com"
  password: "jxtkykpcikdgdccc"
  host: "smtp.qq.com"

jwt:
  isopen: false      #是否开启
  jwt_blacklist_grace_period: 10

openai:
  Key: "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"   #key
  MaxTokens: 2000   #返回最大字数限制
  Temperature: 0.7  #阈值
